### ISSUE TITLE
Why RabbitMQ?

### ISSUE THREAD

**Issue by oladipo** [chukaofili/rabbitmq-ha#1]
I wouldn't choose any other messaging solution either. I'm just curious. Do you use RabbitMQ in production or is this just an experiment?

**Comment by chukaofili** [comment]
Yes i use RabbitMQ in production.

**Comment by oladipo** [comment]
I mean... do you have the cluster in containers or as bare metal deployment w/o docker or k8s ? I am trying to see how risky it really is using RabbitMQ in containerization... or at least get your opinion based on your experience..

**Comment by chukaofili** [comment]
Oh yes, I’m running them in the cluster using kubernetes.

**Comment by oladipo** [comment]
thx!

Any issues so far?

It’s over 1 year now right?

**Comment by chukaofili** [comment]
Yes, over a year. And no problems So far.
